{{- range $s := (include "operators.enabled" . | fromYaml) }}
  {{- if $s.catalogSource }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ $s.catalogSource.name }}
  namespace: {{ $s.namespace }}
spec:
  sourceType: {{ $s.catalogSource.type }}
  image: {{ $s.catalogSource.image }}
  displayName: {{ $s.catalogSource.displayName }}
  publisher: {{ $s.catalogSource.publisher }}
  {{- end }}

  {{- if $s.operatorGroup }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  namespace: {{ $s.namespace }}
  name: {{ $s.name }}
spec:
  {{- $s.operatorGroup | toYaml | nindent 2 }}
  {{- end }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  namespace: {{ $s.namespace }}
  name: {{ $s.name }}
spec:
  name: {{ $s.name }}
  channel: {{ $s.channel }}
  installPlanApproval: Automatic
  source: {{ $s.source }}
  sourceNamespace: {{ $s.sourceNamespace }}
{{- end }}