---
apiVersion: rhtas.redhat.com/v1alpha1
kind: Securesign
metadata:
  namespace: {{ .Values.tas.namespace }}
  name: {{ .Values.tas.name }}
spec:
  fulcio:
    externalAccess:
      enabled: true
    certificate:
      commonName: {{ .Values.tas.fulcio.certificate.commonName }}
      organizationEmail:  {{ .Values.tas.fulcio.certificate.organizationEmail }}
      organizationName: {{ .Values.tas.fulcio.certificate.organizationName }}
    config:
      OIDCIssuers:
        - Issuer: {{ tpl (tpl .Values.tas.fulcio.oidc.issuerURL .) . }}
          IssuerURL: {{ tpl (tpl .Values.tas.fulcio.oidc.issuerURL .) . }}
          ClientID: {{ tpl .Values.tas.fulcio.oidc.clientID . }}
          Type: email
  rekor: 
    externalAccess:
      enabled: true
    rekorSearchUI:
      enabled: true
    signer:
      kms: secret
  trillian:
    database:
      create: true
  tuf:
    externalAccess:
      enabled: true
    port: 80
    keys:
      - name: rekor.pub
      - name: ctfe.pub
      - name: fulcio_v1.crt.pem