{{- $q := .Values.quay }}
{{- if and $q.images.ubi10CurlJq.enabled (not (index $q.images.ubi10CurlJq "pushExistingSecretName")) $q.images.ubi10CurlJq.pushUsername $q.images.ubi10CurlJq.pushPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-ubi10-curl-jq-push
  namespace: {{ $q.namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"{{ tpl $q.configBundle.serverHostname . }}":{"username":"{{ $q.images.ubi10CurlJq.pushUsername | quote }}","password":"{{ $q.images.ubi10CurlJq.pushPassword | quote }}","auth":"{{ printf "%s:%s" $q.images.ubi10CurlJq.pushUsername $q.images.ubi10CurlJq.pushPassword | b64enc }}"}}}
{{- end }}