{{- $q := .Values.quay }}
{{- if and $q.images.ubi10CurlJq.enabled (not (index $q.images.ubi10CurlJq "pushExistingSecretName")) $q.images.ubi10CurlJq.pushUsername $q.images.ubi10CurlJq.pushPassword }}
{{- $user := $q.images.ubi10CurlJq.pushUsername | replace "\\" "\\\\" | replace "\"" "\\\"" }}
{{- $pass := $q.images.ubi10CurlJq.pushPassword | replace "\\" "\\\\" | replace "\"" "\\\"" }}
{{- $auth := printf "%s:%s" $q.images.ubi10CurlJq.pushUsername $q.images.ubi10CurlJq.pushPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-ubi10-curl-jq-push
  namespace: {{ $q.namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"{{ tpl $q.configBundle.serverHostname . }}":{"username":"{{ $user }}","password":"{{ $pass }}","auth":"{{ $auth }}"}}}'
{{- end }}