---
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: {{ .Values.quay.name }}
  namespace: {{ .Values.quay.namespace }}
spec:
  configBundleSecret: config-bundle
  components:
  - kind: postgres
    managed: true
  - kind: objectstorage
    managed: {{ .Values.quay.objectStorageManaged | default false }}
  - kind: redis
    managed: true
  - kind: tls
    managed: true
  - kind: route
    managed: true
  - kind: clair
    managed: true
    overrides:
      volumeSize: {{ .Values.quay.clairVolumeSize | quote }}
  - kind: horizontalpodautoscaler
    managed: false
  - kind: mirror
    managed: false
  - kind: monitoring
    managed: false
  - kind: quay
    managed: false
  - kind: clairpostgres
    managed: false

