{{- $q := .Values.quay }}
{{- if and $q.images.ubi10-curl-jq.enabled (not (index $q.images.ubi10-curl-jq "pushExistingSecretName")) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-ubi10-curl-jq-push
  namespace: {{ $q.namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"{{ tpl $q.configBundle.serverHostname . }}":{"username":"{{ $q.images.ubi10-curl-jq.pushUsername | quote }}","password":"{{ $q.images.ubi10-curl-jq.pushPassword | quote }}","auth":"{{ printf "%s:%s" $q.images.ubi10-curl-jq.pushUsername $q.images.ubi10-curl-jq.pushPassword | b64enc }}"}}}
{{- end }}