{{- $q := .Values.quay }}
{{- $build := $q.images.ubi10CurlJq }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quay-kaniko-builder
  namespace: {{ $q.namespace }}
---
# On OpenShift 4.5+: grant this ServiceAccount the anyuid SCC via ClusterRoleBinding
# (same as: oc adm policy add-scc-to-user anyuid -z quay-kaniko-builder -n quay).
# Requires ClusterRole system:openshift:scc:anyuid (present on OpenShift).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quay-{{ $q.namespace }}-kaniko-builder-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: quay-kaniko-builder
    namespace: {{ $q.namespace }}
