bootstrap:
  gitops:
    source:
      repoUrl: https://github.com/rh-devsecops-ctf/helm.git
      targetRevision: main
  gitea_operator:
    source:
      repoUrl: https://github.com/rh-devsecops-ctf/helm.git
      targetRevision: main
  gitea_operator:
    source:
      repoUrl: https://github.com/rh-devsecops-ctf/helm.git
      targetRevision: main
  argocd:
    namespace:
      syncwave: "-1"
    gitops:
      syncwave: "-1" 
    gitea_operator:
      syncwave: "0"
    gitea:
      syncwave: "1"