bootstrap:
  gitops:
    source:
      repoUrl: https://github.com/rh-devsecops-ctf/helm.git
      targetRevision: main
  gitea_operator:
    source:
      repoUrl: https://github.com/rh-devsecops-ctf/helm.git
      targetRevision: main
  gitea:
    source:
      repoUrl: https://github.com/rh-devsecops-ctf/helm.git
      targetRevision: main