---
apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: {{ .Values.gitea.name }}
  namespace: {{ .Values.gitea.namespace }}
spec:
  giteaImage: {{ .Values.gitea.image.name }}
  giteaImageTag: {{ .Values.gitea.image.tag }}
  giteaImagePullPolicy: {{ .Values.gitea.image.pullPolicy }}
  giteaVolumeSize: 10Gi
  giteaVolumeStorageClass: ''
  postgresqlImage: {{ .Values.gitea.postgres.image.name }}
  postgresqlImageTag: {{ .Values.gitea.postgres.image.tag }}
  postgresqlImagePullPolicy: {{ .Values.gitea.postgres.image.pullPolicy }}
  postgresqlVolumeSize: 10Gi
  postgresqlVolumeStorageClass: ''
  giteaSsl: true

  {{- if .Values.gitea.users.createAdmin }}    
  giteaAdminUser:  {{ .Values.gitea.users.admin.username }}
  giteaAdminPassword: {{ .Values.gitea.users.admin.password }}
  giteaAdminPasswordLength: {{ .Values.gitea.users.admin.passwordLength }}
  giteaAdminEmail: {{ .Values.gitea.users.admin.email }}
  {{- end }}
  
  {{- if .Values.gitea.users.createUsers }}    
  giteaCreateUsers: {{ .Values.gitea.users.createUsers }}
  giteaUserNumber: {{ tpl (printf "%d" .Values.gitea.users.userNumber) . }}
  giteaGenerateUserFormat: {{ tpl .Values.gitea.users.generateUserFormat . }}
  giteaUserPassword: {{ .Values.gitea.users.userPassword }}
  giteaUserPasswordLength: {{ .Values.gitea.users.userPasswordLength }}
  giteaUserEmailDomain: {{ .Values.gitea.users.userEmailDomain }}
  {{- end }}

  {{- if .Values.gitea.repositories.migrateRepositories }}    
  giteaMigrateRepositories: {{ .Values.gitea.repositories.migrateRepositories}}
  giteaRepositoriesList: {{ .Values.gitea.repositories.repositoriesList }} 
  {{- end }}

  giteaDisableRegistration: {{ .Values.gitea.registration.disableRegistration }}
  giteaEnableCaptcha: {{ .Values.gitea.registration.enableCaptcha }}
  giteaAllowCreateOrganization: {{ .Values.gitea.registration.allowCreateOrganization }}
  giteaRegisterEmailConfirm: {{ .Values.gitea.registration.registerEmailConfirm }}
  giteaEnableNotifyMail: {{ .Values.gitea.registration.enableNotifyMail }}


  giteaMailerEnabled: {{ .Values.gitea.mailer.enabled }}
  # giteaMailerFrom: {{ .Values.gitea.mailer.from }}
  # giteaMailerType: {{ .Values.gitea.mailer.type }}
  # giteaMailerHost: {{ .Values.gitea.mailer.host }}
  # giteaMailerTls: {{ .Values.gitea.mailer.tls }}
  # giteaMailerUser: {{ .Values.gitea.mailer.user }}
  # giteaMailerPassword: {{ .Values.gitea.mailer.password }}
  # giteaMailerHeloHostname: {{ .Values.gitea.mailer.heloHostname }}

  # giteaWebhookAllowedHostList: {{ .Values.gitea.Webhook.allowedHostsList }}
  # giteaWebhookSkipTlsVerify: {{ .Values.gitea.Webhook.skipTlsVerify }}