---
# https://github.com/rhpds/gitea-operator/blob/main/config/crd/patches/crd_openapi.yaml
apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: {{ .Values.gitea.name }}
  namespace: {{ .Values.gitea.namespace }}
spec:
  giteaImage: {{ .Values.gitea.image.name }}
  giteaImageTag: {{ .Values.gitea.image.tag }}
  giteaImagePullPolicy: {{ .Values.gitea.image.pullPolicy }}
  giteaVolumeSize: 10Gi
  giteaVolumeStorageClass: ''
  postgresqlImage: {{ .Values.gitea.postgres.image.name }}
  postgresqlImageTag: {{ .Values.gitea.postgres.image.tag }}
  postgresqlImagePullPolicy: {{ .Values.gitea.postgres.image.pullPolicy }}
  postgresqlVolumeSize: 10Gi
  postgresqlVolumeStorageClass: ''
  giteaSsl: true
  giteaHostname: {{ (tpl .Values.gitea.hostname .) | quote }}
  
  {{- if .Values.gitea.users.createAdmin }}
  giteaAdminUser: {{ .Values.gitea.users.admin.username | quote }}
  giteaAdminPassword: {{ .Values.gitea.users.admin.password | quote }}
  {{- end }}
  
  {{- if .Values.gitea.users.createUsers }}
  giteaCreateUsers: {{ .Values.gitea.users.createUsers }}
  giteaUserNumber: {{ .Values.count | int | default 1 }}
  giteaGenerateUserFormat: "{{ .Values.prefix }}%d"
  giteaUserPassword: {{ .Values.gitea.users.userPassword | quote }}
  {{- end }}

  {{- if .Values.gitea.repositories.migrateRepositories }}
  giteaMigrateRepositories: {{ .Values.gitea.repositories.migrateRepositories }}
  giteaRepositoriesList: {{ .Values.gitea.repositories.repositoriesList | toJson }}
  {{- end }}

  giteaDisableRegistration: {{ .Values.gitea.registration.disableRegistration }}
  giteaAllowCreateOrganization: {{ .Values.gitea.registration.allowCreateOrganization }}

  giteaWebhookAllowedHostList: {{ .Values.gitea.Webhook.allowedHostsList }}
  giteaWebhookSkipTlsVerify: {{ .Values.gitea.Webhook.skipTlsVerify }}