{{- if and .Values.gitea.repositories.migrateViaJob.enabled .Values.gitea.repositories.migrateViaJob.repositoriesList .Values.gitea.users.createAdmin }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gitea.name }}-migrate-repos
  namespace: {{ .Values.gitea.namespace }}
  labels:
    app.kubernetes.io/component: gitea-migrate-repos
{{- end }}
