{{- $q := .Values.quay }}
{{- $user := $q.initialSuperuser.username | replace "\\" "\\\\" | replace "\"" "\\\"" }}
{{- $pass := $q.initialSuperuser.password | replace "\\" "\\\\" | replace "\"" "\\\"" }}
{{- $auth := printf "%s:%s" $q.initialSuperuser.username  $q.initialSuperuser.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-pull-secret
  namespace: {{ .Values.gitea.namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"{{ tpl $q.configBundle.serverHostname . }}":{"username":"{{ $user }}","password":"{{ $pass }}","auth":"{{ $auth }}"}}}'