{{- if .Values.minio.bucketsToCreate }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-buckets
  namespace: {{ .Values.minio.namespace }}
  labels:
    app: minio
    component: create-buckets
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: minio
        component: create-buckets
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-buckets
          image: {{ .Values.minio.createBucketsJobImage | default "minio/mc:latest" }}
          command:
            - /bin/sh
            - -c
            - |
              set -e
              MINIO_ENDPOINT="http://minio.{{ .Values.minio.namespace }}.svc.cluster.local:9000"
              echo "Waiting for MinIO at $MINIO_ENDPOINT (initial delay 30s)..."
              sleep 30
              for i in 1 2 3 4 5 6 7 8 9 10 11 12; do
                if mc alias set myminio "$MINIO_ENDPOINT" "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" 2>&1; then
                  echo "MinIO ready."
                  break
                fi
                echo "MinIO not ready (attempt $i/12), retrying in 10s..."
                sleep 10
              done
              mc alias set myminio "$MINIO_ENDPOINT" "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"
              echo "Creating buckets..."
              {{- range .Values.minio.bucketsToCreate }}
              mc mb myminio/{{ . }} --ignore-existing && echo "Bucket {{ . }} ready."
              {{- end }}
              echo "Done."
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName }}
                  key: minio_root_user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName }}
                  key: minio_root_password
{{- end }}
