{{- if .Values.minio.bucketsToCreate }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-buckets
  namespace: {{ .Values.minio.namespace }}
  labels:
    app: minio
    component: create-buckets
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: minio
        component: create-buckets
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-buckets
          image: minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Waiting for MinIO at minio:9000..."
              until mc alias set myminio http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" 2>/dev/null; do
                echo "MinIO not ready, retrying in 5s..."
                sleep 5
              done
              echo "Creating buckets..."
              {{- range .Values.minio.bucketsToCreate }}
              mc mb myminio/{{ . }} --ignore-existing && echo "Bucket {{ . }} ready."
              {{- end }}
              echo "Done."
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName }}
                  key: minio_root_user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName }}
                  key: minio_root_password
{{- end }}
