---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio
  namespace: {{ .Values.minio.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.storageSize }}
  volumeMode: Filesystem